# docker run -it ubuntu bash
# service nginx status
# apt-get update
# apt-get install -y nginx
# service nginx status


FROM ubuntu
RUN apt-get update
RUN apt-get install -y nginx
CMD ["echo", "Run it"]