# TODO: Implement the docker commands as described by the commands


# Use the base: gcr.io/distroless/python3

# Set the working directory to /app

# Copy all the files from your current directory to /app

# Run the hello.py command within the container. Give "/etc" as an argument



# If you implemented all the commands you can build and run the image.
# You should see an output with all the files from the directory "/etc" within the container.
# Hint: if you cannot find the image locally, try binding the container port 80 to your machine's port 80.