# TODO: Implement the docker commands as described by the commands
# Hint: This is a multi-stage Dockerfile



# Use the official python 3 slim image(python:3-slim) as base
# Copy the all files from the current direcotory to /app
# Set the working directory to /app



# Use another base: gcr.io/distroless/python3
# Copy all the files from /app of the build-env to the current /app
# Set the working directory to /app
# Run the hello.py command within the container. Give "/etc" as an argument



# If you implemented all the commands you can build and run the image.
# You should see an output with all the files from the directory "/etc" within the container.
# Hint: if you cannot find the image locally, try binding the container port 80 to your machine's port 80.