apiVersion: v1
kind: Pod
metadata:
  name: configmap-pod-1
spec:
  containers:
    - name: cm-container-1
      image: alpine
      imagePullPolicy: IfNotPresent
      command: [ "/bin/sh", "-c", "env" ]
      env:
        - name: ENV_CITY
          valueFrom:
            configMapKeyRef:
              name: cm
              key: city
  restartPolicy: Never